### ISSUE TITLE
Language Choice

### ISSUE THREAD

**Issue by frankcash** [vishnuravi/clinicalscripts#2]
I personally like that you have chosen Python because it is very widely available (comes with OSX and most Linux distributions) but Clinical Scripts should use a language that has a better implementation of [IEEE 754](http://www.iso.org/iso/iso_catalogue/catalogue_tc/catalogue_detail.htm?csnumber=57469)

**Comment by vishnuravi** [comment]
What would you suggest?

**Comment by frankcash** [comment]
I feel C++/Haskell may be a better choice, but if it doesn't need to be too specific don't worry
